import { test, expect } from '@playwright/test';
const origin = 'http://localhost:3100';
test('create → share → first vote → revisit → independent vote', async ({ page, browser }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/create');
  await page.locator('#title-A').fill('Gladiator'); await page.locator('#subtitle-A').fill('Are you not entertained?');
  await page.locator('#title-B').fill('Braveheart'); await page.locator('#subtitle-B').fill('Freedom!');
  await page.getByLabel('Category').fill('Movie night');
  await expect(page.getByRole('article', { name: 'Gladiator', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Create matchup' }).click();
  await expect(page).toHaveURL(/\/m\/[\w-]{10}\?created=1$/);
  const matchupUrl = page.url().split('?')[0];
  await expect(page.getByText('Your matchup is ready.', { exact: false })).toBeVisible();
  await expect(page.getByText('A clean slate.', { exact: false })).toBeVisible();
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (value: string) => { (window as unknown as { copied: string }).copied = value; } } }); });
  await page.getByRole('button', { name: 'Copy link' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Link copied!' })).toBeVisible();
  expect(await page.evaluate(() => (window as unknown as { copied: string }).copied)).toBe(matchupUrl);
  const voter = await browser.newContext({ viewport: testInfo.project.use.viewport });
  const voterPage = await voter.newPage();
  await voterPage.goto(matchupUrl);
  await expect(voterPage.getByRole('button', { name: 'Vote for Gladiator' })).toBeEnabled();
  const cookie = (await voter.cookies()).find(c => c.name === 'pickside_voter');
  expect(cookie?.httpOnly).toBe(true); expect(cookie?.sameSite).toBe('Lax');
  await voterPage.getByRole('button', { name: 'Vote for Gladiator' }).click();
  await expect(voterPage).toHaveURL(matchupUrl + '/results');
  await expect(voterPage.getByRole('article', { name: 'Gladiator: 100%, 1 votes' })).toBeVisible();
  await expect(voterPage.getByRole('article', { name: 'Braveheart: 0%, 0 votes' })).toBeVisible();
  await expect(voterPage.getByTestId('results-summary')).toContainText('1 vote');
  await voterPage.goto(matchupUrl);
  await expect(voterPage).toHaveURL(matchupUrl + '/results');
  await expect(voterPage.getByText('✓ Your pick', { exact: true })).toBeVisible();
  const slug = matchupUrl.split('/').pop();
  const retries = await Promise.all(Array.from({ length: 8 }, () => voter.request.post(origin + '/api/matchups/' + slug + '/vote', { headers: { Origin: origin }, data: { choice: 'B' } })));
  for (const retry of retries) { expect(retry.ok()).toBe(true); expect((await retry.json()).choice).toBe('A'); }
  await voterPage.reload(); await expect(voterPage.getByTestId('results-summary')).toContainText('1 vote');
  const second = await browser.newContext({ viewport: testInfo.project.use.viewport });
  const secondPage = await second.newPage(); await secondPage.goto(matchupUrl);
  await secondPage.getByRole('button', { name: 'Vote for Braveheart' }).click();
  await expect(secondPage).toHaveURL(matchupUrl + '/results');
  await expect(secondPage.getByRole('article', { name: 'Gladiator: 50%, 1 votes' })).toBeVisible();
  await expect(secondPage.getByRole('article', { name: 'Braveheart: 50%, 1 votes' })).toBeVisible();
  await expect(secondPage.getByTestId('results-summary')).toContainText('2 votes');
  expect(await secondPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await secondPage.screenshot({ path: testInfo.outputPath('results.png'), fullPage: true });
  expect(errors).toEqual([]);
  await voter.close(); await second.close();
});
test('validation, empty results, missing matchups, origin checks and metadata', async ({ page, request }) => {
  const bad = await request.post('/api/matchups', { headers: { Origin: origin }, data: { a: { title: 'Same' }, b: { title: 'same' } } }); expect(bad.status()).toBe(400);
  const crossSite = await request.post('/api/matchups', { headers: { Origin: 'https://other.example' }, data: { a: { title: 'A' }, b: { title: 'B' } } }); expect(crossSite.status()).toBe(403);
  const created = await request.post('/api/matchups', { headers: { Origin: origin }, data: { a: { title: 'Tea' }, b: { title: 'Coffee' } } });
  expect(created.status()).toBe(201); const { slug } = await created.json();
  const anonymous = await request.post('/api/matchups/' + slug + '/vote', { headers: { Origin: origin }, data: { choice: 'A' } }); expect(anonymous.status()).toBe(401);
  await page.goto('/m/' + slug + '/results'); await expect(page.getByRole('heading', { name: 'The floor is open.' })).toBeVisible();
  await expect(page.getByTestId('results-summary')).toContainText('0 votes');
  await page.goto('/m/' + slug); await expect(page).toHaveTitle('Tea vs. Coffee | Pickside');
  await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content', 'Tea vs. Coffee');
  await expect(page.locator('meta[property="og:url"]')).toHaveAttribute('content', origin + '/m/' + slug);
  await expect(page.getByRole('button', { name: 'Vote for Tea' })).toBeEnabled();
  const invalid = await page.request.post('/api/matchups/' + slug + '/vote', { headers: { Origin: origin }, data: { choice: 'C' } }); expect(invalid.status()).toBe(400);
  await page.goto('/m/NoSuch0000'); await expect(page.getByRole('heading', { name: 'Matchup not found.' })).toBeVisible();
});
test('keyboard access and long text remain usable', async ({ page }, testInfo) => {
  await page.goto('/'); await page.keyboard.press('Tab'); await expect(page.getByRole('link', { name: 'Skip to content' })).toBeFocused();
  await page.goto('/create'); await page.locator('#title-A').fill('A'.repeat(80)); await page.locator('#title-B').fill('B'.repeat(80));
  await page.locator('#subtitle-A').fill('A longer description of a contender. '.repeat(3));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('create-long-text.png'), fullPage: true });
});
