'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { matchupSchema } from '@/lib/schema';
import { ChoiceCard } from './choice-card';
export function CreateForm({ signedIn = false }: { signedIn?: boolean }) {
  const router = useRouter(); const [a, setA] = useState({ title: '', subtitle: '' }); const [b, setB] = useState({ title: '', subtitle: '' }); const [category, setCategory] = useState(''); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  async function submit(e: React.FormEvent) { e.preventDefault(); if (pending) return; setError(''); const parsed = matchupSchema.safeParse({ a, b, category }); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } setPending(true); try { const res = await fetch('/api/matchups', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(parsed.data) }); const result = await res.json(); if (!res.ok) throw new Error(result.error); router.push('/m/' + result.slug + '?created=1'); } catch (e) { setError((e as Error).message || 'Couldn’t create your matchup. Try again.'); setPending(false); } }
  return <div className="create-layout"><form onSubmit={submit} className="create-form"><div className="form-intro"><span className="eyebrow">01 / THE CONTENDERS</span><h2>Make it a tough choice.</h2></div>{([{ side: 'A', value: a, setter: setA, placeholder: 'Gladiator' }, { side: 'B', value: b, setter: setB, placeholder: 'Braveheart' }] as const).map(({ side, value, setter, placeholder }) => <fieldset key={side}><legend><span className="field-letter">{side}</span> Choice {side}</legend><label htmlFor={'title-' + side}>Name <span className="required-label">required</span></label><input id={'title-' + side} required maxLength={80} value={value.title} placeholder={placeholder} onChange={e => setter({ ...value, title: e.target.value })}/><label htmlFor={'subtitle-' + side}>Subtitle <span>optional</span></label><input id={'subtitle-' + side} maxLength={120} value={value.subtitle} placeholder={side === 'A' ? 'Are you not entertained?' : 'They may take our lives…'} onChange={e => setter({ ...value, subtitle: e.target.value })}/></fieldset>)}<label htmlFor="category">Category <span>optional</span></label><input id="category" maxLength={32} value={category} placeholder="Movies, food, life’s big questions…" onChange={e => setCategory(e.target.value)}/>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary create-submit" disabled={pending}>{pending ? 'Creating your matchup…' : 'Create matchup'} <span aria-hidden="true">↗</span></button><p className="form-footnote">{signedIn ? 'Saved to My Matchups. Share it with your people.' : 'You’ll get a link to share. No signup needed.'}</p></form><aside className="preview-pane"><div className="preview-label"><span className="live-dot"/>LIVE PREVIEW</div>{category.trim() && <div className="pair-category">{category.trim()}</div>}<div className="preview-cards"><ChoiceCard choice={a} side="A" compact/><span className="vs" aria-hidden="true">VS</span><ChoiceCard choice={b} side="B" compact/></div><p>Your choices. All the personality.<br/>No images needed.</p></aside></div>;
}
